// 389. Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

var findTheDifference = function(s, t) {
    // let sortedS = s.split("").sort()
    // let sortedT = t.split("").sort()
    // for(let i = 0; i < sortedT.length; i++ ){
    //     if(sortedS[i] !== sortedT[i]){
    //         return sortedT[i]
    //     }
    // }
    // console.log(sortedS)
    // console.log(sortedT)
     let mapS = new Map()
     for(let i = 0; i < s.length; i++){
         if(!mapS.has(s[i], 1)){
             mapS.set(s[i], 1)
         }else{
             mapS.set(s[i], mapS.get(s[i])+1)
         }
     }
     console.log(mapS)
     let mapT = new Map()
     for(let i = 0; i < t.length; i++){
         if(!mapT.has(t[i], 1)){
             mapT.set(t[i], 1)
         }else{
             mapT.set(t[i], mapT.get(t[i])+1)
         }
     }
    console.log(mapT)
     for(let [key, value] of mapT){
         if(value !== mapS.get(key)){
             return key
         }
     }
        
};